project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"  
        menu:
          - text: "Pregnancy Risks"
            href: pregnancy-risks/index.qmd
          - text: "Vision Module"
            href: vision-module/index.qmd
          - text: "GIS"
            href: ArcGIS/index.qmd     
          - text: "Design"
            href: Prototype/index.qmd  
          - text: "Scientific Poster"
            href: scientific-poster/index.qmd  
      - text: "Side Projects"
        menu:
          - text: "Ancient Illustrations"
            href: naledi-drawings/index.qmd
          
format:
  html:
    title-prefix: ""
    pagetitle: "{{< meta title >}}"
    css: styles.css
