project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"  
        menu:
        - text: "Pregnancy Risks"
          href: /Porfolio/pregnancy-risks/
        - text: "Vision Module"
          href: /Portfolio/vision-module/
        - text: "GIS"
          href: /Portfolio/ArcGIS/
        - text: "Design"
          href: /Portfolio/Prototype/
        - text: "Scientific Poster"
          href: /Portfolio/scientific-poster/  
      - text: "Side Projects"
        menu:
        - text: "Ancient Illustrations"
          href: /Portfolio/naledi-drawings/

format:
  html:
    title-prefix: ""
    pagetitle: "{{< meta title >}}"
    css: styles.css