project:
  type: website

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"  
        menu:
        - text: "Vision Module"
          href: vision-module/index.qmd
        - text: "GIS"
          href: ArcGIS/index.qmd
        - text: "Design"
          href: Prototype/index.qmd
      - text: "Side Projects"
        menu:
        - text: "Ancient Illustrations"
        - href: Naledi-Drawings/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css